name: Release
on:
    push:
        branches:
            - main

permissions:
    contents: write # to be able to publish a GitHub release
    issues: write # to be able to comment on released issues
    pull-requests: write # to be able to comment on released pull requests

jobs:
    release:
        needs:
            - build
            - changes
        if: ${{ needs.changes.outputs.isNewVersion == 'true' }}
        name: Release
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - uses: actions/download-artifact@v3
              with:
                  path: release-artifacts/

            - uses: codfish/semantic-release-action@v3
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  plugins: |
                      ["@semantic-release/commit-analyzer", "@semantic-release/release-notes-generator", [ "@semantic-release/github", { "assets": ["release-artifacts/**/*"] } ], "@semantic-release/changelog", [ "@semantic-release/git", { "assets": ["CHANGELOG.md"], "message": "chore(release): publish ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}" } ] ]
                  additional-packages: |
                      ["@semantic-release/git"]

    changes:
        runs-on: ubuntu-latest
        outputs:
            isNewVersion: ${{ steps.filter.outputs.new-release-published }}
            newVersion: ${{ steps.filter.outputs.release-version }}

        steps:
            - uses: actions/checkout@v3

            - uses: codfish/semantic-release-action@v3
              id: filter
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  plugins: |
                      ["@semantic-release/commit-analyzer", "@semantic-release/npm", [ "@semantic-release/git", { "assets": ["package.json", "package-lock.json"], "message": "chore(release): bump version to ${nextRelease.version} [skip ci]" } ] ]
                  additional-packages: |
                      ["@semantic-release/git"]
                  dry-run: true

    build:
        needs: changes
        strategy:
            fail-fast: false
            matrix:
                platform: [macos-latest, ubuntu-20.04, windows-latest]

        runs-on: ${{ matrix.platform }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - uses: pnpm/action-setup@v2
              name: Install pnpm
              with:
                  version: 8
                  run_install: false

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - uses: actions/cache@v3
              name: Setup pnpm cache
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              run: pnpm install

            - name: Bump package.json version
              run: npm set version='${{ needs.changes.outputs.newVersion }}'

            - name: install Rust stable
              uses: dtolnay/rust-toolchain@stable

            - name: install dependencies (ubuntu only)
              if: matrix.platform == 'ubuntu-20.04'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

            - uses: tauri-apps/tauri-action@v0

            - run: cd src-tauri/target/release/bundle/deb && ls
              continue-on-error: true

            - uses: actions/upload-artifact@v3
              if: ${{ needs.changes.outputs.isNewVersion == 'true' }}
              with:
                  name: release-${{ needs.changes.outputs.newVersion }}-${{ matrix.platform }}-artifacts
                  path: |
                      src-tauri/target/release/bundle/**/*
                      !src-tauri/target/release/bundle/deb/tauri-release-test_${{needs.changes.outputs.newVersion}}/**/*
                      !src-tauri/target/release/bundle/appimage/tauri-release-test.AppDir/**/*
                      !src-tauri/target/release/bundle/appimage/build_appimage.sh
                  if-no-files-found:
                      ignore

                      # src-tauri/target/release/bundle/nsis/tauri-release-test_${{needs.changes.outputs.newVersion}}_x64_en-US.msi
                      # src-tauri/target/release/bundle/deb/tauri-release-test_${{needs.changes.outputs.newVersion}}_arm64.deb
                      # src-tauri/target/release/bundle/msi/tauri-release-test_${{needs.changes.outputs.newVersion}}_x64-setup.exe
                      # src-tauri/target/release/bundle/appimage/tauri-release-test_${{needs.changes.outputs.newVersion}}_arm64.AppImage
                      # src-tauri/target/release/bundle/dmg/tauri-release-test_${{needs.changes.outputs.newVersion}}_x64.dmg
    # backup:
    #     needs:
    #         - changes
    #         - build
    #     runs-on: ubuntu-latest
    #     if: ${{ needs.changes.outputs.isNewVersion == 'true' }} && ${{ !(needs.build.result == 'success') }}

    #     steps:
    #         - name: Delete stale tag
    #           run: git tag -d v${{needs.changes.outputs.newVersion}}
